Repository freeCodeCamp-2025-Summer-Hackathon/indigo-class, pull requests merged in 2025-07, with the labels that each got.

#18 Feat/basic auth and database setup
  .env.example
  .gitignore
  app/__init__.py
  app/controllers/auth.py
  app/controllers/root.py
  app/models/__init__.py
  app/templates/auth/login.html
  app/templates/auth/profile.html
  app/templates/auth/register.html
  app/templates/base.html
  app/templates/home/admin_dashboard.html
  app/templates/home/dashboard.html
  app/templates/home/index.html
  main.py
  pyproject.toml
  schema.sql
  uv.lock
Labels: enhancement, help wanted, cleanup

#63 Feat/reset passowrd and minor improvements
  .env.example
  .flake8
  app/__init__.py
  app/controllers/affirmations.py
  app/controllers/auth.py
  app/controllers/root.py
  app/models/__init__.py
  app/static/scripts/index.js
  app/templates/_header.html
  app/templates/affirmations/add.html
  app/templates/auth/login.html
  app/templates/base.html
  app/templates/home/index.html
  main.py
  pyproject.toml
  schema.sql
  uv.lock
Labels: enhancement, cleanup, back end

#64 Feature/add user controller
  README.md
  app/__init__.py
  app/controllers/user.py
Labels: enhancement, back end

#100 fix/form-semantics-style
  app/static/styles/components/form.css
  app/static/styles/index.css
  app/static/styles/utilities/alignment.css
  app/templates/auth/login.html
  app/templates/auth/register.html
  app/templates/auth/reset_password_request.html
Labels: front end

#94 fix(page title): match with wireframe (refs #93)
  app/static/styles/base/base.css
Labels: front end

#102 fix: align checkbox with label and match button width to form
  app/static/styles/components/form.css
  app/templates/auth/login.html
Labels: front end

#147 Fix/admin dashboard pages
  app/controllers/affirmations.py
  app/controllers/root.py
  app/static/scripts/dashboard.js
  app/static/styles/index.css
  app/static/styles/pages/admin.css
  app/templates/_header.html
  app/templates/admin/dashboard.html
  app/templates/admin/dashboard_affirmations.html
  app/templates/admin/dashboard_categories.html
  app/templates/admin/dashboard_daily_mail_history.html
  app/templates/admin/dashboard_head.html
  app/templates/admin/dashboard_users.html
Labels: enhancement, cleanup, front end, back end

#148 Fix/seed and affirmation
  app/__init__.py
  app/controllers/affirmations.py
  app/controllers/root.py
  app/globals.py
  app/models/__init__.py
  app/static/scripts/index.js
  app/templates/affirmations/add.html
  app/templates/affirmations/index.html
  app/templates/home/index.html
  seed.py
Labels: bug, back end
